### ISSUE TITLE
User-can-turn-the-car

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] query the DOM to listen for key press for arrows
- [x] car will turn when one of the arrow keys is pressed.
   - [x] up arrow will turn the car to up
   - [x] left arrow will turn the car to left
   - [x] down arrow will turn the car to down
   - [x] right arrow will turn the car to right
