### ISSUE TITLE
user-can-start-the-car

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] position the car top 0 left 0
- [x] set the value to absolute for position property
- [x] when space is pressed will move to the right slightly
   - [x] will keep moving every certain milliseconds
