### ISSUE TITLE
user-can-stop-the-car

### ISSUE THREAD

**Issue by YoonHCho** [YoonHCho/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List

- [x] add a boolean to indicate if the car is moving or not.
- [x] if not moving, when space pressed, start the car
- [x] if moving, when space pressed, stop the car
